url: https://matta-research-group.github.io # the base hostname & protocol for your site
baseurl:  # the subpath of your site, e.g. /blog/
permalink: pretty
title: 'Jekyll Serif'

logo:
  mobile: "images/logo/logo-mobile.svg"
  mobile_height: "32px"
  mobile_width: "32px"
  desktop: "images/logo/logo.svg"
  desktop_height: "32px"
  desktop_width: "120px"

collections:
  services:
    output: true
  team:
    output: true

defaults:
  - scope:
      path: ""
      type: "services"
    values:
      layout: "service"
  - scope:
      path: ""
      type: "team"
    values:
      layout: "team"
mapping:
    provider: openstreetmap
    api_key: AIzaSyDNhj22EqZoDYXSF90FMCQjS-nQx4JG4uI
    zoom: 10
    dimensions:
        width: 600
        height: 400
sass:
  indentWidth: 4
  style: compressed # possible values: nested expanded compact compressed
  precision: 10

plugins:
  - jekyll-environment-variables

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md

theme: jekyll-theme-cayman
