title: Matta Research Group
email: micaela.matta@kcl.ac.uk
description: >- # this means to ignore newlines until "baseurl:"
  Description for the site
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://localhost:4000" # the base hostname & protocol for your site, e.g. http://example.com
JEKYLL_ENV: "development"
address_1: "Britannia House"
address_2: "Kings College London, Chemistry Department"
address_3: "7 Trinity St, London SE1 1DB"

# For jekyll-scholar plugin for Bibtex

collections:
  team:
    output: false
  research:
    output: true
  news:
    output: false
    

scholar:

  last_name: Matta
  first_names: [Micaela, "M"]

  style: apa
  locale: en

  sort_by: year
  order: descending

  source: /_bibliography/
  bibliography: biblio.bib
  bibliography_template: biblio

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"


# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - vendor/
  - assets/foundation/node_modules/
  - assets/foundation/src/
  - assets/foundation/.babelrc
  - assets/foundation/.gitignore
  - assets/foundation/config.yml
  - assets/foundation/gulpfile.babel.js
  - assets/foundation/package.json
  - assets/foundation/readme.md
  - assets/foundation/yarn.lock

defaults:
  - scope:
      path: ""
      type: "research"
    values:
      layout: "single/research"
  